Additional Configuration Parameters
astuff/avt_vimba_camera pull request #101
Opened 2022-08-02 15:54 UTC by PhilippSchmaelzle

Adds the following parameters for configuration:
- ReverseX and Y
- Gamma
- PieceWiseLinearHDR
- DSPSubregion

Tested on ROS1 with AVT Mako223C

2022-08-03 17:02 UTC, icolwell-as commented
Thanks for submitting! I'll try to test it out on our camera soon.

2022-08-04 13:28 UTC, PhilippSchmaelzle commented
No problem!
You made some pretty cool updates from release 1.0.0 onward. Therefore I will no longer use my own fixed driver but start using this one and maybe try to contribute a little.

2022-08-10 14:58 UTC, icolwell-as requested changes
Just tested this today, works great! thanks for submitting!
Only some minor formatting things that need tweaking.

2022-08-10 14:58 UTC, icolwell-as commented on cfg/AvtVimbaCamera.cfg
> +gen.add("exposure_mode",    	str_t,    SensorLevels.RECONFIGURE_RUNNING, "The control for exposure duration.", "Timed", edit_method = exposure_mode_enum)
Can you keep the spacing consistent with the rest of the file?

2022-08-10 14:58 UTC, icolwell-as commented on src/avt_vimba_camera.cpp
> +      configureFeature("ExposureMode", config.exposure_mode ,config.exposure_mode);
It looks like you might be using 4 spaces for indents instead of 2.

2022-08-10 14:58 UTC, icolwell-as commented on src/avt_vimba_camera.cpp
> +    if (on_init_)
Same here, stick to 2 spaces for indents please.

2022-08-11 06:53 UTC, PhilippSchmaelzle commented
thx for the review! I fixed the indents

2022-08-11 07:24 UTC, PhilippSchmaelzle commented
Sorry for the 1000 commits. I had to use GitHub Web interface and it was a mess with tabs and spaces...

2022-08-23 15:14 UTC, icolwell-as approved these changes
Thanks!

2022-08-24 13:34 UTC, dvangeyn-as approved these changes

2022-08-25 15:40 UTC, merged