Adding framerate control for Vimba v6
astuff/avt_vimba_camera pull request #121
Opened 2023-05-20 16:25 UTC by MikoMikarro

2023-05-23 14:19 UTC, icolwell-as commented
Thanks @MikoMikarro for the PR! Can you provide some more context and details in the PR description?
For example:
- Why is this new parameter needed?
- What problem did you run into that this is solving?
- What camera hardware are you using?

2023-05-25 16:47 UTC, MikoMikarro commented
Hi, we added the new name for the frame parameter that was added with the last firmware, this fixes some of the problems related to issue #119 .  Without this change in the parameter name, we couldn't change the camera's frame rate. I've also left uncommented the last name so it should work without any problem in the previous and current firmware.

I've also added the parameter that allows to use free run or fix the framerate.

Our team is using the G-201 camera: https://www.alliedvision.com/en/camera-selector/detail/manta/g-201/

2023-05-25 19:11 UTC, icolwell-as requested changes
Thanks for the details! these change make sense to me, just a small nitpick on the formatting.

Thanks again for taking the time to submit a PR!

2023-05-25 19:11 UTC, icolwell-as commented on cfg/AvtVimbaCamera.cfg
> +gen.add("acquisition_rate_enable",       bool_t, SensorLevels.RECONFIGURE_RUNNING, "Allows to fix acquisition rate, if available", False)
Can you adjust the whitespace formatting here so that bool_t aligns vertically with all the other field types?

2023-05-26 14:33 UTC, icolwell-as approved these changes, later dismissed

2023-05-26 15:36 UTC, shan-as commented on launch/Mako_G-319.launch
> +    <arg name="acquisition_rate_enable" default="$(arg acquisition_rate_enable)"/>
`value` instead of `default` here ?

2023-05-26 16:04 UTC, shan-as approved these changes
Have not tested on a camera

2023-05-26 16:54 UTC, dvangeyn-as approved these changes

2023-05-29 13:51 UTC, merged